### PR TITLE
Changed binary libraries names for windows and linux and they are *no…

### PR DESCRIPTION
**Pull request by Nitaym**
…rmally* named Lerc64.dll/so

### CODE REVIEW

**Comment by tmaurer3** [comment]
Hi Nitaym, yes, it used to be Lerc64.dll. Going back to times we built both for 32 and 64 bit. Nowadays it is 64 bit only, so it makes more sense to drop it and go with the shorter "Lerc.dll".

**Comment by Nitaym** [comment]
Hi @tmaurer3,

I definitely agree on the naming conventions!

However, on the PyPI version, the files are still named Lerc64. Is this a PyPI thing?

**Comment by tmaurer3** [comment]
@Nitaym  I don't know. Perhaps they have a name clash - see https://libraries.io/pypi/lerc-control .  Is there a way to ask that question to the PyPI folks? They might have their ways how to resolve name clashes, if that is the reason.

**Comment by Nitaym** [comment]
@tmaurer3 - It doesn't look like the case.

We've tested it here and verified that when installing through `pip3 install` in multiple computers the libraries are named Lerc64.so. Tested on Linux only though.

Do you see different results?

**Comment by Nitaym** [comment]
Hi @tmaurer3,

Please see the following log - Ran it on a clean docker:

```
docker run -it python /bin/bash
root@dfd546a08901:/# python
Python 3.9.0 (default, Nov 18 2020, 13:28:38)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
Collecting lerc
  Downloading lerc-0.1.0.tar.gz (567 kB)
     |████████████████████████████████| 567 kB 675 kB/s
Building wheels for collected packages: lerc
  Building wheel for lerc (setup.py) ... done
  Created wheel for lerc: filename=lerc-0.1.0-py3-none-any.whl size=571698 sha256=482b545e205058fed50cc9d7b346185995c288f4bef1a984a718030ddc8888e9
  Stored in directory: /root/.cache/pip/wheels/b7/90/75/f9d8dc6029709fc93f82845afcbedc97af2a8c68eb1f51f423
Successfully built lerc
Installing collected packages: lerc
Successfully installed lerc-0.1.0
root@dfd546a08901:/# python
Python 3.9.0 (default, Nov 18 2020, 13:28:38)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lerc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/lerc/__init__.py", line 1, in <module>
    from ._lerc import *
  File "/usr/local/lib/python3.9/site-packages/lerc/_lerc.py", line 38, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
>>> exit()
root@dfd546a08901:/# import numpy
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/360.
root@dfd546a08901:/# pip install numpy
Collecting numpy
  Downloading numpy-1.19.4-cp39-cp39-manylinux2010_x86_64.whl (14.5 MB)
     |████████████████████████████████| 14.5 MB 8.5 MB/s
Installing collected packages: numpy
Successfully installed numpy-1.19.4
root@dfd546a08901:/# python
Python 3.9.0 (default, Nov 18 2020, 13:28:38)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lerc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/lerc/__init__.py", line 1, in <module>
    from ._lerc import *
  File "/usr/local/lib/python3.9/site-packages/lerc/_lerc.py", line 48, in <module>
    lercDll = ct.CDLL (os.path.join(dir_path, 'Lerc.so'))
  File "/usr/local/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.9/site-packages/lerc/Lerc.so: cannot open shared object file: No such file or directory
```

**Comment by tmaurer3** [comment]
@Nitaym  "lerc-0.1.0" sounds outdated. There have been commits after the last release tag was set that might be relevant here. Can you run your thing using the current Lerc master instead of the last Lerc release? Also take a look at the last PR before yours. I'm not familiar with docker installs. If this should work on current master, adding a new release tag might fix it.

**Comment by Nitaym** [comment]
@tmaurer3 Installing master works. Looks like you just need to push the latest version into PyPI!

**Comment by tmaurer3** [comment]
@Nitaym  Will do. Thanks for pointing this out!

**Comment by Nitaym** [comment]
Hi @tmaurer3, I see PyPi still has an older version
https://pypi.org/project/lerc/

Any update on the upgrade?

**Pull request closed without merging**
