### PR TITLE
remove leaflet sample and make landing page more concise

### PR DESCRIPTION
**Pull request by jgravois**
* removed leaflet sample altogether.  (we can continue playing around in [jgravois/lerc-leaflet](https://github.com/jgravois/lerc-leaflet) until we have something we're happy with.  this will ensure there is no more chatter in the issues here unrelated to the actual LERC spec).
* wrote a new section called *What is LERC* with the most concise explanation i could think of
* rewrote the LERC API reference as a markdown table
* moved principles or lerc, history etc. into their own file in the doc/ directory.

you can see the updated README [here](https://github.com/jgravois/lerc/blob/patch/README.md) prior to review prior to merging
happy to take notes prior to this being merged if anything needs tweaking.

### CODE REVIEW

**Comment by tmaurer3** [comment]
Thanks, John!  Looks awesome!

Only for the first sentence, let me try this:
“LERC is an Open Source format for rapid encoding and decoding images of any pixel type (not just Byte or RGB). It preserves the precision of the original input image within user defined error bounds. The user sets the maximum compression error per pixel allowed, the only parameter to the encoder.

Feel free to improve on the wording.

**Comment by jgravois** [comment]
@ajturner can you help us with this?  we're trying to craft a concise elevator pitch type statement to explain what makes LERC unique.

my first guess/attempt
>  LERC is an Open Source format which supports rapid encoding/decoding with *dynamic* image compression and preserves the precision of the original raster.

@tmaurer3's clarification
> LERC is an Open Source format for rapid encoding and decoding images of any pixel type (not just Byte or RGB). It preserves the precision of the original input image within user defined error bounds. The user sets the maximum compression error per pixel allowed, the only parameter to the encoder.

i think we're best off landing somewhere in the middle in terms of word count/complexity.

**Comment by jgravois** [comment]
maybe this?

> LERC is an open-source image format which supports rapid encoding and decoding for any pixel type.  Users set the maximum compression error per pixel while encoding, so the precision of the original input image is preserved (within user defined error bounds).

**Comment by tmaurer3** [comment]
Ok. Let’s put it in like this. If someone comes up with something even better, we can still change it again.

**Comment by jgravois** [comment]
:+1:

**Pull request merged**
