### PR TITLE
src/LercLib/Lerc_c_api.h: resync it with include/Lerc_c_api.h

### PR DESCRIPTION
**Pull request by rouault**
Note: the duplication of both files is confusing, and has indeed just confused a libtiff user!

### CODE REVIEW

**Comment by kmilos** [comment]
Should probably drop this and have a different PR that removes duplication and just uses `include/Lerc_c_api.h` everywhere.

**Comment by hobu** [comment]
> the same time before the library gets wider adoption...

With libtiff 4.3.0 supporting LERC, I will be working to include the LERC library in @conda-forge so we can use it for the full geo stack there. It would be nice to have another tagged release that is coincident with any things that have been recently added or fixed.

**Comment by tmaurer3** [comment]
@kmilos @rouault  Lerc has no external dependencies and doesn't need any include paths. The dll can be built with the files in src/LercLib alone. I'd like to keep it that way. I can move these 2 header files into an include folder in LercLib to make them more visible.

**Comment by kmilos** [comment]
This is about other projects using Lerc, I'm quite aware it doesn't have dependencies. I presume you want to make it as easy and portable as possible, no?

For example, I wanted to package it for mingw so the LibTIFF update could use it, but would have to patch it a bit... it's better to handle it at the source.

**Comment by tmaurer3** [comment]
@kmilos  Sure. And we are fixing the export / import dll thing. Still, if the include files are in src/LercLib/include, why is that a problem?

**Comment by kmilos** [comment]
I guess it matters less where the header lives in your source tree, as long as you don't have two copies.

**Pull request merged**
